### ISSUE TITLE
Deactivation of provenance capture has no effect on publishing to the log file

### ISSUE THREAD

**Issue by ineart** [CamFlow/camflowd#13]
After activation of provenance capture with **camflow --track-file <file> propagate** provenance is captured in e.g. audit.log file. After deactivation the log file size continues to grow. Even if i run **camflow -e false** to deactivate the whole provenance capture, the information is still logged. Is it possible to stop logging somehow?

**Comment by michael-hahn** [comment]
It is likely that CamFlow has already stopped capturing provenance; however, there are still some provenance records in the relayFS buffer that are being copied into the log file. Would you please confirm that this is not the case? (You can, for example, try to wait a while and see if the file stops growing.)

**Comment by ineart** [comment]
Unfortunately the file continues to grow. And it grows pretty fast, aprox. 1Gb in 10 minutes
![workrave provenance](https://user-images.githubusercontent.com/44093146/46876215-09a67c00-ce3e-11e8-9533-b148208d311b.PNG)

I'm trying to get some provenance for the program named Workrave [http://www.workrave.org/](url). I did not expect that such small programm produces so much data. May be i should activate some more filters to reduce the ammount of data?

Additionally to the initial config i activated 2 relation_filters:
![camflow settings](https://user-images.githubusercontent.com/44093146/46876432-918c8600-ce3e-11e8-9ce0-a8e1b73995de.PNG)

**Comment by ineart** [comment]
... And after restart of the VM the log is gone and new one with the same name is created.

**Comment by michael-hahn** [comment]
Thank you for bringing this issue to our attention.
We will look into the problem, but if you do not mind, please inform us of the version of CamFlow and Ubuntu (mainly the kernel version) that you are currently using. 
Thank you.

Regarding your follow-up comment, this behavior is expected.

**Comment by ineart** [comment]
![camflow_ubuntu_version](https://user-images.githubusercontent.com/44093146/46878143-cd294f00-ce42-11e8-88e6-e3d0a74aa7a5.PNG)

**Comment by michael-hahn** [comment]
Thank you. We will try to reproduce the issue and respond to you ASAP.
The size of provenance data depends on how the tracked application interacts with the underlying system. It is likely that it frequently requests system's service.
If you have a specific task in mind, you might want to minimal the space overhead by tracking only specific activities. You can also try to inspect the audit log and see what irrelevant activities are abundant and filter them out as well.

**Comment by ineart** [comment]
Thank you for a quick response and your suggestions. To inspect the log file was my next idea.

**Comment by tfjmp** [comment]
Close the issue as this seems ok at this point.
