### ISSUE TITLE
w3c compliance of epoch attribute in generated json file

### ISSUE THREAD

**Issue by ineart** [CamFlow/camflowd#14]
In generated json file the attribute **epoche** is present:
![camflow epoch attribute](https://user-images.githubusercontent.com/44093146/46879503-876e8580-ce46-11e8-9526-929cde45614f.png)

I'm not sure if this is w3c compliant. If i try to validate one selected object from the generated log file with [https://openprovenance.org/services/view/validator](url), it does not validate:
![camflow prov validation excepiton](https://user-images.githubusercontent.com/44093146/46879732-17acca80-ce47-11e8-98a3-82a5617a2fa5.PNG)

If i remove **epoch** attribute, validation is almost ok, except of some merge constraints:
![camflow prov validation](https://user-images.githubusercontent.com/44093146/46879888-7b36f800-ce47-11e8-84fc-8f1c25a7897c.PNG)

Is it an expected behaviour? I did not find anything in relation to **epoch** configuration in the documentation.

**Comment by tfjmp** [comment]
Indeed, epoch should be pre-fixed. I will fix this.

**Comment by tfjmp** [comment]
Should have been fixed by the following commit:
https://github.com/CamFlow/libprovenance/commit/1a52c6a619b3956f1d207225aa88bcdd887592bd

Should be rolled out in the next release cycle.
