### ISSUE TITLE
Logfile continues to grow fast after one call on wget

### ISSUE THREAD

**Issue by ineart** [CamFlow/camflowd#16]
After camflow installation and executing `sudo camflow --track-file /bin/wget propagate`  and then `wget www.google.de` like on  [documentation page](https://github.com/CamFlow/documentation/blob/master/docs/tutorial.md) described, the provenance logfile starts to grow very fast. After disable the tracking on wget, log file continues to grow.

![camflwo wget on fedora](https://user-images.githubusercontent.com/44093146/50058600-c7b9ef00-017a-11e9-9cc4-736e072389e3.gif)

Gif above was made on Fedora 29 with
![image](https://user-images.githubusercontent.com/44093146/50058800-08ffce00-017e-11e9-8004-f88f64fb2210.png)

I tested this behaviour with all installation types:

1. Fedora-specific: using packagecloud (Fedora 27);
2. building the kernel on the local machine (Fedora 28, Fedora 29) ;
3. using vagrant to set up a virtual machine
like described on this [page](https://github.com/CamFlow/documentation/blob/master/docs/installation.md).

Sometimes the logfile starts to grow even by just executing `sudo camflow --track-file /bin/wget propagate` without the actuall call on wget. This behaviour does not make any sense for me, because the object of interest was not even activ.

**Comment by tfjmp** [comment]
Propagate taint file to be tracked. It does not track a single program (in your case `wget`), but use it as the starting point for tracking.

In the case of a fedora desktop what tends to happen is that there is a service that index file written to disk for "search" purpose. This service is tracked, its interaction with other services get tracked etc.... Other programs could end up being tracked through interacting with `/bin/wget`, e.g., anything that would be doing file scan etc...

If you are interested in only the traces generated by `wget`, you may want to try something like:
`camflow --track-file /bin/wget true`

**Comment by ineart** [comment]
OK, i understand that with propagate wget is just an entry point for tracking. The thing is, i thought that this behavior was different under camflow version 0.4.4. I just tested camflow version v0.4.4 and v0.4.5 with 2 virtual boxes with the same OS Ubuntu 16.04.05. 

In v0.4.4 with `sudo camflow --track-file /usr/bin/wget propagate`  `wget www.google.com` generated a small log file of 331,1kb
![wget with camflow v0_4_4](https://user-images.githubusercontent.com/44093146/50095231-54b18680-0215-11e9-8dc8-7b9c30b0266f.PNG)

Then i run the same commands on v0.4.5 and became a huge logfile, which did not stop to grow even after disabling the tracking:
![wget with camflow v0_4_5 big logfile](https://user-images.githubusercontent.com/44093146/50095464-e7522580-0215-11e9-8638-b6e01413780a.PNG)

Then i restarted the VM again an gave another try on v0.4.5. And somehow it was fine. Now the same commands generate a small file:
![wget with camflow v0_4_5 small logfile](https://user-images.githubusercontent.com/44093146/50095660-4d3ead00-0216-11e9-8a94-bc0256d50f37.PNG)

So I suppose, some process in the chain was propagated and was still doing something, like you described in the case of fedora desktop. But does it mean that, if the provenance tracking is triggered with propagate on one object of interest, then it can end in a endless amount of information from sub and sub-sub- etc. processes, which were derived from the original object of interest even if the tracking is set to false afterwards? Will camflow still gather provenance from sub-processes, if the tracking on original object was already disabled? Can this behavior be avoided? I mean in the most of time you can not know what will be derived from the original object and how deep it will go.

**Comment by tfjmp** [comment]
> So I suppose, some process in the chain was propagated and was still doing something, like you described in the case of fedora desktop. But does it mean that, if the provenance tracking is triggered with propagate on one object of interest, then it can end in a endless amount of information from sub and sub-sub- etc. processes, which were derived from the original object of interest even if the tracking is set to false afterwards?

That is correct.

> Will camflow still gather provenance from sub-processes, if the tracking on original object was already disabled? 

Yes

> Can this behavior be avoided?

Depends what you want to achieve exactly. One solution is to turn off capture all together once you have the trace corresponding to the program you care a bout (i.e. `camflow -e false`).

> I mean in the most of time you can not know what will be derived from the original object and how deep it will go.

Possibility to define your tracking rules more precisely is something I have been thinking about, but it is not implemented at the moment. However, using what we describe in our paper (http://camflow.org/publications/ccs-2018.pdf) it is perfectly doable.

The "query" that defines propagation is here:
https://github.com/CamFlow/camflow-dev/blob/master/security/provenance/propagate.c

It is as simple as it can be, it can be modified to suit your needs. Developing something that is configurable and general is obviously a more complex problem.

I am happy to discuss what you are trying to achieve and try to help out with some "dirty" fix or a cleaner long-term solution.

**Comment by ineart** [comment]
> Depends what you want to achieve exactly.

The big goal is to collect provenance information about different services or applications without changing them. This requirement should be implemented in the context of [SenseCare ](https://www.ftk.de/en/projects/senscare)project, in which prov data to different object of interest like created or deleted files, information Flow, etc. should be captured to support reproducibility on different levels.

As part of a master's thesis, I am to develop a prototype for collecting provenance data using an example application. The first idea was to use a small application [Workrave](http://www.workrave.org/) but I had some issues with a very fast growing logfile. Then I decided to try your documentation example `wget`.

In `wget` example in the first step the information of interest could be the input url and the retrieved file as output and in the second step the information flow in the system. 

_What i am trying to understand is, if this information could be collected with camflow?_ I think, it is possible and i hope to finde a solution to do it without much overhead.

> If you are interested in only the traces generated by wget, you may want to try something like:
`camflow --track-file /bin/wget true`

If i run camflow with `camflow --track-file /bin/wget true`, the generated logfile will not grow like with `propagate` option and is relative small ([audit.log](https://github.com/CamFlow/camflowd/files/2715563/audit.log)). But neither information to input url nor output file are present in the logfile. Runing the provenance tracking with `propagate` ends often with a continuous fast growing logfile, in which a lot of information from different linux system processes are captured.

> The "query" that defines propagation is here:
https://github.com/CamFlow/camflow-dev/blob/master/security/provenance/propagate.c

If I understood that correctly, then with  `camflow --track-file /bin/wget true` only the direct neighbors must be recorded (**+1** level), because nothing should be propagated from this file/programm. The whole provenance is 3 JSONs in the logfile:

**1st JSON:**
![zeile 1](https://user-images.githubusercontent.com/44093146/50523170-df746a00-0ace-11e9-978c-7180219d0df7.PNG)

**2nd JSON:**
![zeile 2 mit wget entity](https://user-images.githubusercontent.com/44093146/50526072-ed7eb680-0adf-11e9-8f9c-ee3bb9fecc52.PNG)

**3rd JSON:**
![zeile 3](https://user-images.githubusercontent.com/44093146/50523208-16e31680-0acf-11e9-949e-5ef25d76f4bf.PNG)

The `wget path entity` can be found in the 2nd JSON(marked with red on the left side in 2nd picture). This one is connected with `process_memory entity` which is connected with a `task` (marked with green). The green task itself is connected with the `entity` on top (marked with orange). There is no information logged for this entity. _Why this information is not present? And why the orange entyty is actually logged? Is it not already **+2** level from the `wget entity` perspective and should not be captured at all?_

On the right side there is also another `task` (marked with blue), which is connected with the same orange `entity`. This one has connections to other `process_memory` entities and to one `/bin/bash path entity`. `/bin/bash` is set to opaque. _Why does it still appears in the logfile?_  As you can see in the 2nd picture, this task has no direct connection to the `wget entity`. _Why this whole blue task branch is present? Is ist no even **+3** level from the `wget entity` perspective?_

_Can you also explain how the JSONs are actually grouped by? When camflow creates a new JSON entry in the logfile? Is it triggered by size, time or somehow different? The 3rd JSON is just a new version of one entity from 2nd JSON, why camflow stored it in an extra JSON?_

> I am happy to discuss what you are trying to achieve and try to help out with some "dirty" fix or a cleaner long-term solution.

I am very grateful for your help :)

**Comment by tfjmp** [comment]
Response not necessarily in order.

> Can you also explain how the JSONs are actually grouped by? When camflow creates a new JSON entry in the logfile? Is it triggered by size, time or somehow different? The 3rd JSON is just a new version of one entity from 2nd JSON, why camflow stored it in an extra JSON?

It is triggered by the size. There is an option to support SPADE JSON format (https://github.com/ashish-gehani/SPADE/wiki/Reporting-provenance-using-JSON), I found this format more intuitive if that is of help.

You should also merge the 3 JSONs into one, then convert them into a visualisation.

![example](https://user-images.githubusercontent.com/1970355/50556739-f2588b80-0cd4-11e9-8278-184ab289c090.png)

I see the /bin/bash which appears, while it should not. I have logged an issue (https://github.com/CamFlow/camflow-dev/issues/79).

What wget command are you using? `wget www.google.com`

If that is the case, I will try to debug what is going wrong and should hopefully come back in a few days with something that is working as one would expect.

**Comment by ineart** [comment]
> There is an option to support SPADE JSON format (https://github.com/ashish-gehani/SPADE/wiki/Reporting-provenance-using-JSON), I found this format more intuitive if that is of help.

In fact, it looks a little better.

> You should also merge the 3 JSONs into one, then convert them into a visualisation.

What do you use to visualize the SPADE JSON?

> What wget command are you using? wget www.google.com

Exactly.

> If that is the case, I will try to debug what is going wrong and should hopefully come back in a few days with something that is working as one would expect.

Perfect! Best regards for the New Year!

**Comment by tfjmp** [comment]
> What do you use to visualize the SPADE JSON?

I believe there is a tool to visualise SPADE data: https://github.com/ashish-gehani/SPADE/wiki/Creating-Graphviz-output

If you meant how did I generate the output I have shown, I used the W3C output there: http://camflow.org/demo

_Note: you need to add JSON entry one by one or use some tools to merge them._

**Comment by tfjmp** [comment]
Hi @ineart,

I believe I fixed most of the issue you were encountering.

`sudo camflow --track-file /bin/wget` should now lead to graph who look like what you expect. Sorry the feature was not properly tested while we made changes in other areas of the system.

The slightly bad news is that the graph is now obviously slightly bigger ;). However, you can configure the system to exclude interactions you do not care about.

You should be able to see program arguments:
![params](https://user-images.githubusercontent.com/1970355/50587683-c37a1b00-0e76-11e9-8bd8-73e7a85ac68e.png)

Shared libraries e.g.:
![library](https://user-images.githubusercontent.com/1970355/50587741-0cca6a80-0e77-11e9-9e73-d76d45933864.png)

Configuration files:
![config](https://user-images.githubusercontent.com/1970355/50587903-a265fa00-0e77-11e9-98e9-f035e635c4f0.png)

And Socket interactions:
![socket](https://user-images.githubusercontent.com/1970355/50587971-e6f19580-0e77-11e9-8d9d-fd6cab9ebdfb.png)

I hope this does cover the type of information you were expecting to obtain. I am of course happy to provide further help if I can.

I would appreciate if you could test the hotfix before I release it. You can do so as follow (on a Fedora machine):
```
sudo dnf groupinstall 'Development Tools'
sudo dnf install ncurses-devel cmake clang gcc-c++ wget git openssl-devel zlib ruby bison flex patch mosquitto
git clone https://github.com/CamFlow/camflow-dev.git
git checkout tracking-fix
make prepare
make config # select relevant modules in security
make compile # patience, password will be asked during compilation
make install # patience, password will be asked during installation
```

The kernel need to be compiled so it will take a while. I should release a hotfix in the next fewdays once I am convinced I fixed all problems.

**Comment by ineart** [comment]
Hi @tfjmp,

> I would appreciate if you could test the hotfix before I release it. You can do so as follow (on a Fedora machine):

Originally, I tried Fedora and Ubuntu, but after Fedora did the same thing, I switched back to Ubuntu. At the time, I suspected a difference between camflow 0.4.4 and 0.4.5 and wanted to compare these two versions on Ubuntu 16.04, as the 0.4.4 version did not produce large logfiles in my first tests.

So i tried to install the tracking-fix by running following commands (output is in this logfile 
[tracking-fix output.txt](https://github.com/CamFlow/camflowd/files/2721676/tracking-fix.output.txt)):

`sudo apt-get -y install build-essential #line 1 in logfile`
`sudo apt-get -y install libncurses-dev cmake clang g++ wget git libssl-dev bc nano patch mosquitto bison flex ruby # line 8 in logfile`
`sudo apt-get -y install libelf-dev # line 365 in logfile`
`git clone https://github.com/CamFlow/camflow-dev.git #line 385 in logfile`
`cd camflow-dev # line 396 in logfile`
`git checkout tracking-fix #line 401 in logfile`
`make prepare # line 406 in logfile`
`make config # line 709, left default settings`
`make compile # line 750 in logfile`
`make install # line 5000 in logfile`

During installation I bacame some errors and do not know if the installation was complete successful:
![error bei make install 2_2](https://user-images.githubusercontent.com/44093146/50608404-de777a00-0ecc-11e9-8277-5894c712ef7a.PNG)

After that the installation ended pretty fast (s. logfile line 5000-5187).

I tested it both on Ubuntu with camflow 0.4.5 and on fresh Ubuntu. Both were the same.

Then I rebooted the system and checked camflow. It was present in version 0.4.6:
![uname after hotfix install](https://user-images.githubusercontent.com/44093146/50609031-cd2f6d00-0ece-11e9-85c1-cdcb4bae1401.PNG)
But i am not sure if it was installed properly. When i run the installation with 0.4.4 and 0.4.5 releases as described in your [documentation](https://github.com/CamFlow/documentation/blob/master/docs/installation.md) on Ubuntu 16.04, the whole process took much more time and, I think, I had no errors.

Do you recommend to use Fedora and try the installation again?

I tried to run `wget www.google.com` and check the result anyway. The manual merge of all the JSONs is time consuming. I tried [http://camflow.org/demo](url) with merge of 2 JSONs. It works fine. What do you mean with:
> Note: you need to add JSON entry one by one

Do you mean manual merge or where can i add them?

**Comment by ineart** [comment]
In your [documentation](https://github.com/CamFlow/documentation/blob/master/docs/installation.md) the command 
`sudo apt-get -y install libncurses-dev cmake clang g++ wget git libssl-dev bc nano patch mosquitto bison flex`
for ubuntu is missing word `ruby`. I noticed that because I got some errors at first.

**Comment by tfjmp** [comment]
> In your documentation the command
> `sudo apt-get -y install libncurses-dev cmake clang g++ wget git libssl-dev bc nano patch mosquitto bison flex`
> for ubuntu is missing word ruby. I noticed that because I got some errors at first.

Fixed in https://github.com/CamFlow/documentation/commit/3f4d6ebc9e01672a1a980a7455a2662cb75d6e6c

**Comment by tfjmp** [comment]
> Do you recommend to use Fedora and try the installation again?

Generally yes. My main development environment is Fedora so the "dev" build process is made to work there. 

> Do you mean manual merge or where can i add them?

If what you described above merge the JSON that is fine.

**Comment by ineart** [comment]
> Generally yes. My main development environment is Fedora so the "dev" build process is made to work there.

Which Fedora version do you use? I tried to install the fix on Fedora 27 and got also an error on `make install`:
![3_error bei make compile on feodra 27_2](https://user-images.githubusercontent.com/44093146/50664286-d42cad00-0fac-11e9-9c5b-bd9b15a0576f.PNG)
`make install` command took less than a minute.

Like on ubuntu the version has changed but I had to install camflow-cli by myself:
![3_error bei make compile on feodra 27_3](https://user-images.githubusercontent.com/44093146/50664623-01c62600-0fae-11e9-9599-6b5ad964e1e3.PNG)

After the installation `camflow -v` retrieved:
![3_error bei make compile on feodra 27_4](https://user-images.githubusercontent.com/44093146/50664720-5cf81880-0fae-11e9-81bb-1201bcc29435.PNG)

I wanted to test provenance collection on `wget`, but i noticed that `camflowd.ini` in `/etc/` was missing:
![3_error bei make compile on feodra 27_5](https://user-images.githubusercontent.com/44093146/50665026-7057b380-0faf-11e9-8f51-2651c4c368e5.PNG)

I assume that `camflowd` module does not need to be installed separately or does it?

**Comment by tfjmp** [comment]
Did you get an error during `make prepare`? (if you retry on your current machine in `camflow-dev` do `rm -rf build`).

**Comment by tfjmp** [comment]
I have made some more test on my end, it seems that most of the issue I could see have been fixed. If you are also satisfied with the results, I will try to get a release out over the WE.

**Comment by ineart** [comment]
> Did you get an error during `make prepare`? (if you retry on your current machine in `camflow-dev` do `rm -rf build`).

`make prepare` runs without errors. I tried it again.

**Comment by tfjmp** [comment]
Issue should have been fixed by latest release: https://github.com/CamFlow/camflow-dev/commit/033a540bd1e605c607d32169a4732035a0d86de3

Open new issue on https://github.com/CamFlow/camflow-dev if there is any further problem.
